### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Eeems** [irth/regenesis#7]
What license is this under? Without one specified, all rights are reserved by the author.

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

**Comment by irth** [comment]
Hi, thanks, I meant to do that but I forgot. I added a MIT license to both irth/golibgen and regenesis. I'm on a little bit of a hiatus with this project, feel free to have fun with it now that's it licensed properly!
